version: '2'
services:
  combats:
    container_name: combats
    image: djklim87/combats:latest
    env_file:
      - access.env
    restart: always
    ports:
      - 8080:80
  mysql:
    container_name: mysql
    image: mysql:5.7
    env_file:
      - access.env
    restart: always
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
